-- Hero-specific data for the bot to take advantage of

-- Initial observation chances so the bot can buy better items on round 1
HERO_OBSERVATION_DATA = {
	["npc_dota_hero_abaddon"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_alchemist"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.75,
		["high_consecutive_disable"] = 0.75,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_axe"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_beastmaster"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.4,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_brewmaster"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.5,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_bristleback"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_centaur"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.5,
		["high_consecutive_disable"] = 0.5,
		["high_magic_damage"]        = 0.2,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_chaos_knight"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.4,
		["high_consecutive_disable"] = 0.4,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.5,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_rattletrap"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.5,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.3,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_dark_seer"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.2,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_doom_bringer"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.9,
		["high_consecutive_disable"] = 0.9,
		["high_magic_damage"]        = 0.5,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_dragon_knight"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.5,
		["high_consecutive_disable"] = 0.5,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_earth_spirit"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.5,
		["high_consecutive_disable"] = 0.5,
		["high_magic_damage"]        = 0.5,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_earthshaker"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.8,
		["high_consecutive_disable"] = 0.5,
		["high_magic_damage"]        = 0.2,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_elder_titan"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.5,
		["high_consecutive_disable"] = 0.5,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_huskar"] = {
		["high_status_resistance"]   = 0.3,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.6,
		["high_pure_damage"]         = 0.6,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_wisp"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_kunkka"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.4,
		["high_consecutive_disable"] = 0.4,
		["high_magic_damage"]        = 0.3,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_legion_commander"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.8,
		["high_consecutive_disable"] = 0.8,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_life_stealer"] = {
		["high_status_resistance"]   = 0.2,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_lycan"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.2,
		["high_consecutive_disable"] = 0.2,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_magnataur"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.7,
		["high_consecutive_disable"] = 0.7,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_mars"] = {
		["high_status_resistance"]   = 0.3,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.5,
		["high_consecutive_disable"] = 0.5,
		["high_magic_damage"]        = 0.3,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_night_stalker"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_omniknight"] = {
		["high_status_resistance"]   = 0.9,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_phoenix"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.8,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_pudge"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.5,
		["high_consecutive_disable"] = 0.5,
		["high_magic_damage"]        = 0.5,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_sand_king"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.5,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_slardar"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.7,
		["high_consecutive_disable"] = 0.7,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_spirit_breaker"] = {
		["high_status_resistance"]   = 0.4,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.5,
		["high_consecutive_disable"] = 0.5,
		["high_magic_damage"]        = 0.2,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_sven"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_tidehunter"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_shredder"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.5,
		["high_pure_damage"]         = 0.3,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_tiny"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.3,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_treant"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_tusk"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_abyssal_underlord"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_undying"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.2,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_skeleton_king"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_antimage"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_arc_warden"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.5,
		["high_consecutive_disable"] = 0.5,
		["high_magic_damage"]        = 0.5,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_bloodseeker"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_bounty_hunter"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_broodmother"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_clinkz"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.4,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_drow_ranger"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_ember_spirit"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.3,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_faceless_void"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.5,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_gyrocopter"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_juggernaut"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.2,
		["high_consecutive_disable"] = 0.2,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_lone_druid"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_luna"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.4,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_medusa"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.2,
		["high_consecutive_disable"] = 0.2,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_meepo"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_mirana"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.2,
		["high_consecutive_disable"] = 0.2,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_morphling"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.2,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_monkey_king"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.2,
		["high_consecutive_disable"] = 0.2,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_naga_siren"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_nyx_assassin"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.4,
		["high_consecutive_disable"] = 0.4,
		["high_magic_damage"]        = 0.4,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_pangolier"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_phantom_assassin"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.4,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_phantom_lancer"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.8,
	},
	["npc_dota_hero_razor"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_riki"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_nevermore"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.2,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_slark"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.4,
		["high_consecutive_disable"] = 0.4,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_sniper"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_spectre"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.3,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_templar_assassin"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_terrorblade"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_troll_warlord"] = {
		["high_status_resistance"]   = 0.3,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_ursa"] = {
		["high_status_resistance"]   = 0.5,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_vengefulspirit"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_venomancer"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.4,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_viper"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.4,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_weaver"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.4,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_ancient_apparition"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.4,
		["high_consecutive_disable"] = 0.4,
		["high_magic_damage"]        = 0.6,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_bane"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.8,
		["high_consecutive_disable"] = 0.8,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.5,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_batrider"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.5,
		["high_magic_damage"]        = 0.4,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_chen"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_crystal_maiden"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.3,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_dark_willow"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.5,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.4,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_dazzle"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.4,
		["high_consecutive_disable"] = 0.4,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_death_prophet"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.2,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_disruptor"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.7,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_enchantress"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.4,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_enigma"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.8,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_grimstroke"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_invoker"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.3,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_jakiro"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.4,
		["high_pure_damage"]         = 0.3,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_keeper_of_the_light"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_leshrac"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.7,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_lich"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_lina"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.3,
		["high_pure_damage"]         = 0.3,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_lion"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.6,
		["high_consecutive_disable"] = 0.6,
		["high_magic_damage"]        = 0.6,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_furion"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_necrolyte"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.8,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_ogre_magi"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.4,
		["high_consecutive_disable"] = 0.4,
		["high_magic_damage"]        = 0.5,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_oracle"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_obsidian_destroyer"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.7,
		["high_burst_damage"]        = 0.5,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_puck"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.3,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_pugna"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.6,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_queenofpain"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_rubick"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.5,
		["high_consecutive_disable"] = 0.5,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_shadow_demon"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.2,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_shadow_shaman"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.6,
		["high_consecutive_disable"] = 0.6,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_silencer"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.5,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_skywrath_mage"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.8,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_storm_spirit"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.4,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_techies"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.5,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_tinker"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.5,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_visage"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_warlock"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.3,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_windrunner"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.3,
		["high_consecutive_disable"] = 0.3,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_winter_wyvern"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.1,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_witch_doctor"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.5,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.3,
		["mana_burn"]                = 0.1,
	},
	["npc_dota_hero_zuus"] = {
		["high_status_resistance"]   = 0.1,
		["high_evasion"]             = 0.5,
		["high_disable_amount"]      = 0.1,
		["high_consecutive_disable"] = 0.1,
		["high_magic_damage"]        = 0.8,
		["high_pure_damage"]         = 0.1,
		["high_burst_damage"]        = 0.1,
		["mana_burn"]                = 0.1,
	},
}